# Server Configuration
server.port=8080

# Active Profile Configuration
spring.profiles.active=local

# JPA Common Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Supabase JWK Set (JWKS) URI for public key validation
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SUPABASE_JWK_SET_URI:https://wltfcolsglrpvcacxzbu.supabase.co/auth/v1/.well-known/jwks.json}
spring.security.oauth2.resourceserver.jwt.jws-algorithms=ES256



