-- 1. Create paths table
CREATE TABLE paths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(1000),
    category VARCHAR(255),
    managed_by VARCHAR(255)
);

-- 2. Create topics table
CREATE TABLE topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path_id BIGINT REFERENCES paths(id) ON DELETE CASCADE,
    title VARCHAR(255),
    description VARCHAR(1000),
    duration VARCHAR(255),
    category VARCHAR(255),
    is_completed BOOLEAN NOT NULL DEFAULT FALSE
);

-- 3. Create subtopics table
CREATE TABLE subtopics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT REFERENCES topics(id) ON DELETE CASCADE,
    title VARCHAR(255),
    content TEXT,
    order_index INTEGER NOT NULL
);

-- 4. Create users table
CREATE TABLE users (
    id VARCHAR(255) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    full_name VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    avatar VARCHAR(255),
    role VARCHAR(255),
    bio VARCHAR(255),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE
);

-- 5. Create email_verification_tokens table
CREATE TABLE email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE
);
