-- 1. Create paths table
CREATE TABLE paths (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255),
    description VARCHAR(1000),
    category VARCHAR(255),
    managed_by VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED'
);

-- 2. Create topics table
CREATE TABLE topics (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    path_id UUID REFERENCES paths(id) ON DELETE CASCADE,
    title VARCHAR(255),
    description VARCHAR(1000),
    duration VARCHAR(255),
    category VARCHAR(255),
    order_index INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED'
);

-- 3. Create subtopics table
CREATE TABLE subtopics (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    topic_id UUID REFERENCES topics(id) ON DELETE CASCADE,
    title VARCHAR(255),
    content TEXT,
    order_index INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
    version INTEGER NOT NULL DEFAULT 1
);

-- 4. Create content_blocks table
CREATE TABLE content_blocks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    subtopic_id UUID NOT NULL REFERENCES subtopics(id) ON DELETE CASCADE,
    order_index INTEGER NOT NULL,
    type VARCHAR(20) NOT NULL,
    body TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 5. Create quiz_questions table
CREATE TABLE quiz_questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    block_id UUID NOT NULL REFERENCES content_blocks(id) ON DELETE CASCADE,
    kind VARCHAR(20) NOT NULL,
    prompt TEXT NOT NULL,
    options JSONB,
    correct_answer TEXT NOT NULL,
    explanation TEXT,
    points INTEGER NOT NULL DEFAULT 5
);

-- 6. Create users table
CREATE TABLE users (
    id VARCHAR(255) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    full_name VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    avatar VARCHAR(255),
    role VARCHAR(50) NOT NULL DEFAULT 'USER',
    bio VARCHAR(255),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE
);

-- 7. Create email_verification_tokens table
CREATE TABLE email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE
);

-- 8. Create user_learning_preferences table
CREATE TABLE user_learning_preferences (
    user_id VARCHAR(255) PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Kolkata',
    current_streak INT NOT NULL DEFAULT 0,
    longest_streak INT NOT NULL DEFAULT 0,
    last_activity_date DATE,
    total_points INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 9. Create user_topic_progress table
CREATE TABLE user_topic_progress (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    topic_id UUID NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    path_id UUID NOT NULL REFERENCES paths(id) ON DELETE CASCADE,
    status VARCHAR(16) NOT NULL DEFAULT 'NOT_STARTED',
    completed_at TIMESTAMPTZ,
    UNIQUE (user_id, topic_id)
);
CREATE INDEX idx_topic_progress_user_path ON user_topic_progress (user_id, path_id);

-- 10. Create user_subtopic_progress table
CREATE TABLE user_subtopic_progress (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subtopic_id UUID NOT NULL REFERENCES subtopics(id) ON DELETE CASCADE,
    topic_id UUID NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMPTZ,
    content_version_answered INTEGER,
    first_attempt_correct BOOLEAN DEFAULT TRUE,
    UNIQUE (user_id, subtopic_id)
);
CREATE INDEX idx_subtopic_progress_user_topic ON user_subtopic_progress (user_id, topic_id);

-- 11. Create user_learning_daily_activity table
CREATE TABLE user_learning_daily_activity (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    activity_date DATE NOT NULL,
    first_activity_at TIMESTAMPTZ NOT NULL,
    last_activity_at TIMESTAMPTZ NOT NULL,
    qualifying_event_count INT NOT NULL DEFAULT 0,
    points_earned INTEGER NOT NULL DEFAULT 0,
    UNIQUE (user_id, activity_date)
);
CREATE INDEX idx_daily_activity_user_date ON user_learning_daily_activity (user_id, activity_date DESC);

-- 12. Create subtopic_notes table
CREATE TABLE subtopic_notes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subtopic_id UUID NOT NULL REFERENCES subtopics(id) ON DELETE CASCADE,
    content TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, subtopic_id)
);
CREATE INDEX idx_subtopic_notes_user ON subtopic_notes (user_id);

-- 13. Create topic_bookmarks table
CREATE TABLE topic_bookmarks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    topic_id UUID NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, topic_id)
);
CREATE INDEX idx_topic_bookmarks_user ON topic_bookmarks (user_id);

-- 14. Create shared_snippets table
CREATE TABLE shared_snippets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    short_id VARCHAR(12) NOT NULL UNIQUE,
    code_hash VARCHAR(64) NOT NULL UNIQUE,
    language VARCHAR(30) NOT NULL,
    code TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_accessed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_shared_snippets_short_id ON shared_snippets (short_id);
CREATE INDEX idx_shared_snippets_code_hash ON shared_snippets (code_hash);

