-- 1. Create paths table
CREATE TABLE paths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(1000),
    category VARCHAR(255),
    managed_by VARCHAR(255)
);

-- 2. Create topics table
CREATE TABLE topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path_id BIGINT REFERENCES paths(id) ON DELETE CASCADE,
    title VARCHAR(255),
    description VARCHAR(1000),
    duration VARCHAR(255),
    category VARCHAR(255)
);

-- 3. Create subtopics table
CREATE TABLE subtopics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT REFERENCES topics(id) ON DELETE CASCADE,
    title VARCHAR(255),
    content TEXT,
    order_index INTEGER NOT NULL
);

-- 4. Create users table
CREATE TABLE users (
    id VARCHAR(255) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    full_name VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    avatar VARCHAR(255),
    role VARCHAR(255),
    bio VARCHAR(255),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE
);

-- 5. Create email_verification_tokens table
CREATE TABLE email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE
);

-- 6. Create user_learning_preferences table
CREATE TABLE user_learning_preferences (
    user_id VARCHAR(255) PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Kolkata',
    current_streak INT NOT NULL DEFAULT 0,
    longest_streak INT NOT NULL DEFAULT 0,
    last_activity_date DATE,
    total_points INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 7. Create user_topic_progress table
CREATE TABLE user_topic_progress (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    topic_id BIGINT NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    path_id BIGINT NOT NULL REFERENCES paths(id) ON DELETE CASCADE,
    status VARCHAR(16) NOT NULL DEFAULT 'NOT_STARTED',
    completed_at TIMESTAMPTZ,
    UNIQUE (user_id, topic_id)
);
CREATE INDEX idx_topic_progress_user_path ON user_topic_progress (user_id, path_id);

-- 8. Create user_subtopic_progress table
CREATE TABLE user_subtopic_progress (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subtopic_id BIGINT NOT NULL REFERENCES subtopics(id) ON DELETE CASCADE,
    topic_id BIGINT NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMPTZ,
    UNIQUE (user_id, subtopic_id)
);
CREATE INDEX idx_subtopic_progress_user_topic ON user_subtopic_progress (user_id, topic_id);

-- 9. Create user_learning_daily_activity table
CREATE TABLE user_learning_daily_activity (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    activity_date DATE NOT NULL,
    first_activity_at TIMESTAMPTZ NOT NULL,
    last_activity_at TIMESTAMPTZ NOT NULL,
    qualifying_event_count INT NOT NULL DEFAULT 0,
    UNIQUE (user_id, activity_date)
);
CREATE INDEX idx_daily_activity_user_date ON user_learning_daily_activity (user_id, activity_date DESC);
