-- ============================================================================
-- learnNow — baseline schema
-- ============================================================================
--
-- The single migration the database is built from. It is a consolidation: the
-- schema arrived incrementally during development, but none of those steps ever
-- ran outside a developer's machine, so there is no deployment history worth
-- preserving and a great deal of noise worth removing. What is written here is
-- the end state, as if it had been designed this way — no column added and then
-- dropped, no table created and then migrated away from.
--
-- Two consolidations in particular are worth knowing about, because the
-- intermediate shapes still turn up in older branches and in conversation:
--
--   * Topics used to carry a path_id column *and* sit in a path_topics join
--     table, leaving two sources of truth for one relationship. Only the join
--     table survives. Nothing may reintroduce that column.
--   * Notes and bookmarks used to be one table per target kind — subtopic
--     notes, topic notes, DSA problem notes, topic bookmarks. They are now one
--     `notes` table and one `bookmarks` table, each with a nullable FK per
--     target kind and a CHECK that exactly one is set. The reasoning is in
--     SECTION 5.
--
-- Conventions used throughout:
--
--   * Surrogate keys are UUID, generated by the database. Users are the one
--     exception: their id is an application-issued string, since accounts may
--     originate from an external identity provider.
--   * Timestamps are TIMESTAMPTZ. Never TIMESTAMP — learners span time zones
--     and streaks are computed against a stored per-user zone.
--   * Every foreign key is indexed. Postgres does not do this automatically,
--     and without it each cascade delete degrades into a sequential scan.
--   * Anything owned by a user cascades from it, so deleting an account removes
--     its data in one statement.
--   * Status and type columns are constrained by CHECK rather than left as free
--     text, so a typo in application code fails at write time rather than
--     becoming a row nothing will ever match.
--   * Tables and non-obvious columns carry COMMENT metadata, which surfaces in
--     psql (\d+) and any schema browser.
--
-- Ordering below follows dependency order: course content, then identity, then
-- per-user progress, then the DSA sheet, then the learner-authored tables that
-- reference both content trees.
-- ============================================================================

-- gen_random_uuid() lives in pgcrypto before Postgres 13 and in core after.
-- Requesting it explicitly keeps this migration portable across both.
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- ----------------------------------------------------------------------------
-- Shared trigger for updated_at.
--
-- Some tables map updated_at through JPA and some do not, which would leave the
-- column silently stale on the ones that do not -- worse than having no column
-- at all, since it reads as trustworthy. Maintaining it in the database makes
-- it true for every writer, including migrations and manual fixes.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_updated_at() IS 'BEFORE UPDATE trigger; stamps updated_at so the column cannot go stale.';


-- ============================================================================
-- SECTION 1 — Course content
--
-- A path is a course. A topic is a chapter within it, and a subtopic is a
-- lesson within that. Paths and topics are many-to-many: a topic such as
-- "HTTP fundamentals" belongs in several courses without being duplicated.
-- ============================================================================

CREATE TABLE paths (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    category    VARCHAR(255),
    managed_by  VARCHAR(255),
    status      VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED'
                CONSTRAINT ck_paths_status CHECK (status IN ('DRAFT', 'PUBLISHED')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  paths IS 'A learning path — one course, containing an ordered set of topics.';
COMMENT ON COLUMN paths.status IS 'DRAFT is visible only to admins; PUBLISHED is public.';
COMMENT ON COLUMN paths.managed_by IS 'Attribution shown to learners, e.g. the authoring team.';

CREATE INDEX idx_paths_status ON paths (status);


CREATE TABLE topics (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    duration    VARCHAR(255),
    category    VARCHAR(255),
    -- Fallback ordering for a topic viewed outside any path. Ordering *within*
    -- a path lives on path_topics, because the same topic can sit at a
    -- different position in each course that includes it.
    order_index INTEGER NOT NULL DEFAULT 1,
    status      VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED'
                CONSTRAINT ck_topics_status CHECK (status IN ('DRAFT', 'PUBLISHED')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  topics IS 'A chapter of study. Shared across paths via path_topics; a topic has no single owning path.';
COMMENT ON COLUMN topics.duration IS 'Human-readable estimate shown in the UI, e.g. "45 mins". Not used for arithmetic.';
COMMENT ON COLUMN topics.order_index IS 'Fallback ordering only. Position within a path is path_topics.order_index.';

CREATE INDEX idx_topics_status ON topics (status);


CREATE TABLE path_topics (
    path_id     UUID NOT NULL REFERENCES paths(id)  ON DELETE CASCADE,
    topic_id    UUID NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    order_index INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (path_id, topic_id)
);

COMMENT ON TABLE  path_topics IS 'Single source of truth for path membership, with per-path ordering.';
COMMENT ON COLUMN path_topics.order_index IS 'Position of this topic within this path. The same topic may be ordered differently elsewhere.';

-- The composite primary key already indexes (path_id, ...), so only the reverse
-- direction and the ordered read need their own indexes.
CREATE INDEX idx_path_topics_topic ON path_topics (topic_id);
CREATE INDEX idx_path_topics_order ON path_topics (path_id, order_index);


CREATE TABLE subtopics (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    topic_id          UUID NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    title             VARCHAR(255) NOT NULL,
    content           TEXT,
    order_index       INTEGER NOT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED'
                      CONSTRAINT ck_subtopics_status CHECK (status IN ('DRAFT', 'PUBLISHED')),
    -- Bumped on each publish. Progress rows record the version a learner
    -- answered against, so substantive edits can be told apart from typo fixes.
    version           INTEGER NOT NULL DEFAULT 1,
    -- Deliberately unconstrained. Both are content taxonomy supplied by course
    -- authors through the bulk importer, so a CHECK here would turn a new label
    -- into a migration and reject an otherwise valid import at the database
    -- layer, where the error cannot be reported usefully. Validate at the API
    -- boundary instead. Conventional values: level is beginner | intermediate |
    -- advanced; track is concept | lab | project.
    level             VARCHAR(20) NOT NULL DEFAULT 'beginner',
    track             VARCHAR(30) NOT NULL DEFAULT 'concept',
    -- JSON array of subtopic titles that should be completed first. Advisory,
    -- not enforced by the application.
    prerequisites     JSONB NOT NULL DEFAULT '[]',
    video_url         VARCHAR(512),
    -- Zero is permitted: an author may legitimately not have estimated a lesson.
    estimated_minutes INTEGER NOT NULL DEFAULT 5
                      CONSTRAINT ck_subtopics_minutes CHECK (estimated_minutes >= 0),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  subtopics IS 'A single lesson. The smallest unit a learner completes.';
COMMENT ON COLUMN subtopics.version IS 'Incremented on publish; compared against user_subtopic_progress.content_version_answered.';
COMMENT ON COLUMN subtopics.prerequisites IS 'JSON array of prerequisite subtopic titles. Advisory.';
COMMENT ON COLUMN subtopics.level IS 'Author-supplied difficulty label. Open vocabulary; validated at the API boundary, not here.';
COMMENT ON COLUMN subtopics.track IS 'Author-supplied lesson kind. Open vocabulary; validated at the API boundary, not here.';

-- Covers both the foreign key and the ordered read of a topic's lessons.
CREATE INDEX idx_subtopics_topic_order ON subtopics (topic_id, order_index);


CREATE TABLE subtopic_code_snippets (
    id              VARCHAR(100) NOT NULL,
    subtopic_id     UUID NOT NULL REFERENCES subtopics(id) ON DELETE CASCADE,
    language        VARCHAR(30) NOT NULL,
    label           VARCHAR(255),
    code            TEXT NOT NULL,
    expected_output TEXT,
    runnable        BOOLEAN NOT NULL DEFAULT TRUE,
    editable        BOOLEAN NOT NULL DEFAULT TRUE,
    order_index     INTEGER NOT NULL DEFAULT 1,
    -- Author-assigned id, unique only within its subtopic, so imports can
    -- reference snippets by a stable readable name.
    PRIMARY KEY (subtopic_id, id)
);

COMMENT ON TABLE  subtopic_code_snippets IS 'Runnable examples attached to a lesson, shown in the embedded playground.';
COMMENT ON COLUMN subtopic_code_snippets.runnable IS 'Whether the learner may execute it, as opposed to only reading it.';
COMMENT ON COLUMN subtopic_code_snippets.expected_output IS 'Optional; lets the UI show what correct output looks like.';

CREATE INDEX idx_snippets_subtopic ON subtopic_code_snippets (subtopic_id);


CREATE TABLE content_blocks (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    subtopic_id UUID NOT NULL REFERENCES subtopics(id) ON DELETE CASCADE,
    order_index INTEGER NOT NULL,
    type        VARCHAR(20) NOT NULL
                CONSTRAINT ck_content_blocks_type
                    CHECK (type IN ('markdown', 'quiz', 'callout', 'code')),
    body        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  content_blocks IS 'Ordered blocks making up a lesson body.';
COMMENT ON COLUMN content_blocks.type IS 'markdown and callout use body; quiz draws from quiz_questions instead.';

CREATE INDEX idx_content_blocks_subtopic_order ON content_blocks (subtopic_id, order_index);


CREATE TABLE quiz_questions (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    block_id       UUID NOT NULL REFERENCES content_blocks(id) ON DELETE CASCADE,
    kind           VARCHAR(20) NOT NULL
                   CONSTRAINT ck_quiz_questions_kind
                       CHECK (kind IN ('mcq', 'true_false', 'fill_blank')),
    prompt         TEXT NOT NULL,
    -- JSON array of choices. Null for fill_blank.
    options        JSONB,
    -- Compared case-insensitively, server-side only. Never sent to a client
    -- before the attempt is settled.
    correct_answer TEXT NOT NULL,
    explanation    TEXT,
    points         INTEGER NOT NULL DEFAULT 5
                   CONSTRAINT ck_quiz_questions_points CHECK (points >= 0)
);

COMMENT ON TABLE  quiz_questions IS 'Questions belonging to a quiz content block. Grading is server-side.';
COMMENT ON COLUMN quiz_questions.correct_answer IS 'Withheld from responses until the attempt is settled, so a wrong answer cannot reveal it.';
COMMENT ON COLUMN quiz_questions.points IS 'Awarded on the first correct attempt only. See user_quiz_attempts.';

CREATE INDEX idx_quiz_questions_block ON quiz_questions (block_id);


-- ============================================================================
-- SECTION 2 — Identity and credentials
--
-- Every token table stores only a SHA-256 hash of the value handed to the user,
-- so a database disclosure yields nothing that can be replayed.
-- ============================================================================

CREATE TABLE users (
    -- Application-issued rather than database-generated, because an account may
    -- originate from an external identity provider.
    id             VARCHAR(255) PRIMARY KEY,
    email          VARCHAR(255) NOT NULL,
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    full_name      VARCHAR(255),
    -- Null for accounts that authenticate only through Google.
    password_hash  VARCHAR(255),
    google_sub     VARCHAR(255) UNIQUE,
    avatar         VARCHAR(512),
    role           VARCHAR(50) NOT NULL DEFAULT 'USER'
                   CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN')),
    bio            VARCHAR(500),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    -- Incremented to invalidate every access token issued so far, without
    -- needing a database read on each request.
    token_version  INTEGER NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  users IS 'Learner and administrator accounts.';
COMMENT ON COLUMN users.id IS 'Application-issued identifier, not a database sequence.';
COMMENT ON COLUMN users.password_hash IS 'BCrypt. Null when the account authenticates only via Google.';
COMMENT ON COLUMN users.google_sub IS 'Google subject claim. Unique so one Google identity maps to one account.';
COMMENT ON COLUMN users.token_version IS 'Bumped on password reset; refuses refresh tokens minted before the change.';

-- Addresses are matched case-insensitively throughout, so uniqueness has to be
-- enforced the same way. A plain UNIQUE would let Ada@x.com and ada@x.com
-- coexist and create two accounts for one mailbox.
CREATE UNIQUE INDEX uq_users_email_lower ON users (LOWER(email));


CREATE TABLE email_verification_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  email_verification_tokens IS 'Single-use email confirmation grants. Purged nightly once used or expired.';
COMMENT ON COLUMN email_verification_tokens.token_hash IS 'SHA-256 of the token in the emailed link; the token itself is never stored.';

CREATE INDEX idx_email_verification_user    ON email_verification_tokens (user_id);
CREATE INDEX idx_email_verification_expires ON email_verification_tokens (expires_at);


CREATE TABLE password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  password_reset_tokens IS 'Single-use password reset grants, valid for one hour.';

CREATE INDEX idx_password_reset_user    ON password_reset_tokens (user_id);
CREATE INDEX idx_password_reset_expires ON password_reset_tokens (expires_at);


CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  refresh_tokens IS 'Renewal grants. Rows exist so a session can actually be revoked, which a bare JWT cannot be.';
COMMENT ON COLUMN refresh_tokens.revoked IS 'Set on sign-out, on rotation, and for every row on password reset.';

CREATE INDEX idx_refresh_token_user    ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_token_expires ON refresh_tokens (expires_at);


-- ============================================================================
-- SECTION 3 — Progress and gamification
--
-- Completion is one-way: points are awarded on the transition and never
-- reversed, so a reversible transition would be a way to mint them.
-- ============================================================================

CREATE TABLE user_learning_preferences (
    user_id            VARCHAR(255) PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    -- Streaks are day-boundary sensitive, so "today" must be evaluated in the
    -- learner's own zone rather than the server's.
    timezone           VARCHAR(64) NOT NULL DEFAULT 'Asia/Kolkata',
    current_streak     INTEGER NOT NULL DEFAULT 0
                       CONSTRAINT ck_prefs_current_streak CHECK (current_streak >= 0),
    longest_streak     INTEGER NOT NULL DEFAULT 0
                       CONSTRAINT ck_prefs_longest_streak CHECK (longest_streak >= 0),
    last_activity_date DATE,
    total_points       INTEGER NOT NULL DEFAULT 0
                       CONSTRAINT ck_prefs_total_points CHECK (total_points >= 0),
    -- Optimistic lock. Point awards are read-modify-write, so without it two
    -- concurrent awards silently lose one of the two increments.
    version            BIGINT NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  user_learning_preferences IS 'Per-learner settings and lifetime gamification totals.';
COMMENT ON COLUMN user_learning_preferences.timezone IS 'IANA zone id. Streak day boundaries are evaluated in it.';
COMMENT ON COLUMN user_learning_preferences.version IS 'JPA @Version. Guards concurrent point awards.';


CREATE TABLE user_topic_progress (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      VARCHAR(255) NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
    topic_id     UUID NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    -- Denormalised deliberately: records which path the learner was working
    -- through when they completed it, which path_topics cannot answer once a
    -- topic belongs to several.
    path_id      UUID NOT NULL REFERENCES paths(id)  ON DELETE CASCADE,
    status       VARCHAR(16) NOT NULL DEFAULT 'NOT_STARTED'
                 CONSTRAINT ck_utp_status
                     CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED')),
    completed_at TIMESTAMPTZ,
    CONSTRAINT uq_utp_user_topic UNIQUE (user_id, topic_id)
);

COMMENT ON TABLE  user_topic_progress IS 'A learner''s state for one topic. One row per user and topic.';
COMMENT ON COLUMN user_topic_progress.path_id IS 'The path the learner was in at the time; a topic can belong to several.';

CREATE INDEX idx_utp_user_path_status ON user_topic_progress (user_id, path_id, status);
CREATE INDEX idx_utp_topic            ON user_topic_progress (topic_id);


CREATE TABLE user_subtopic_progress (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                  VARCHAR(255) NOT NULL REFERENCES users(id)     ON DELETE CASCADE,
    subtopic_id              UUID NOT NULL REFERENCES subtopics(id) ON DELETE CASCADE,
    -- Denormalised so "how many lessons of this topic are done" is a single
    -- indexed count rather than a join back through subtopics.
    topic_id                 UUID NOT NULL REFERENCES topics(id)    ON DELETE CASCADE,
    completed                BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at             TIMESTAMPTZ,
    content_version_answered INTEGER,
    first_attempt_correct    BOOLEAN,
    CONSTRAINT uq_usp_user_subtopic UNIQUE (user_id, subtopic_id)
);

COMMENT ON TABLE  user_subtopic_progress IS 'A learner''s state for one lesson.';
COMMENT ON COLUMN user_subtopic_progress.topic_id IS 'Denormalised from subtopics to keep per-topic completion counts a single indexed read.';
COMMENT ON COLUMN user_subtopic_progress.content_version_answered IS 'subtopics.version at completion, so later edits can be detected.';

CREATE INDEX idx_usp_user_topic_completed ON user_subtopic_progress (user_id, topic_id, completed);
CREATE INDEX idx_usp_subtopic             ON user_subtopic_progress (subtopic_id);


CREATE TABLE user_quiz_attempts (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        VARCHAR(255) NOT NULL REFERENCES users(id)          ON DELETE CASCADE,
    question_id    UUID NOT NULL REFERENCES quiz_questions(id) ON DELETE CASCADE,
    is_correct     BOOLEAN NOT NULL,
    points_awarded INTEGER NOT NULL DEFAULT 0
                   CONSTRAINT ck_quiz_attempt_points CHECK (points_awarded >= 0),
    attempted_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- This constraint is the actual enforcement of first-attempt-only scoring.
    -- An application-level check alone still loses the race between two
    -- concurrent submissions for the same question.
    CONSTRAINT uq_quiz_attempt_user_question UNIQUE (user_id, question_id)
);

COMMENT ON TABLE  user_quiz_attempts IS 'One row per learner per question. Its existence is what stops points being farmed by replay.';
COMMENT ON COLUMN user_quiz_attempts.points_awarded IS 'Non-zero only on a correct first attempt.';

CREATE INDEX idx_quiz_attempt_user ON user_quiz_attempts (user_id);


CREATE TABLE user_learning_daily_activity (
    id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- A calendar date in the learner's own time zone, not UTC.
    activity_date          DATE NOT NULL,
    first_activity_at      TIMESTAMPTZ NOT NULL,
    last_activity_at       TIMESTAMPTZ NOT NULL,
    qualifying_event_count INTEGER NOT NULL DEFAULT 0,
    points_earned          INTEGER NOT NULL DEFAULT 0
                           CONSTRAINT ck_daily_points CHECK (points_earned >= 0),
    CONSTRAINT uq_daily_user_date UNIQUE (user_id, activity_date)
);

COMMENT ON TABLE  user_learning_daily_activity IS 'Daily rollup driving the streak calendar and weekly leaderboard.';
COMMENT ON COLUMN user_learning_daily_activity.activity_date IS 'Local date in the learner''s configured zone.';
COMMENT ON COLUMN user_learning_daily_activity.qualifying_event_count IS 'Actions that count towards keeping a streak alive.';

CREATE INDEX idx_daily_activity_user_date ON user_learning_daily_activity (user_id, activity_date DESC);


-- ============================================================================
-- SECTION 4 — DSA sheet
--
-- A structured problem sheet as a module of its own, a sibling of the course
-- catalogue rather than a special case of it: nothing here references paths,
-- topics or subtopics.
--
-- The content spine is sheet -> step -> section -> problem, where sections
-- nest to any depth. Around the problem sit four tables of editorial depth;
-- the two that make the coding workspace possible are dsa_harnesses and
-- dsa_test_cases. The rest would be recognisable to anyone who has read
-- SECTION 1.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Content spine
-- ----------------------------------------------------------------------------

CREATE TABLE dsa_sheets (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug         VARCHAR(120) NOT NULL UNIQUE,
    title        VARCHAR(255) NOT NULL,
    description  VARCHAR(1000),
    playlist_url VARCHAR(512),
    status       VARCHAR(16) NOT NULL DEFAULT 'DRAFT'
                 CONSTRAINT ck_dsa_sheets_status CHECK (status IN ('DRAFT', 'PUBLISHED')),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  dsa_sheets IS 'A problem sheet. More than one is allowed by design; one ships.';
COMMENT ON COLUMN dsa_sheets.playlist_url IS 'YouTube playlist backing the sheet. Problems deep-link into it by position.';

CREATE INDEX idx_dsa_sheets_status ON dsa_sheets (status);


CREATE TABLE dsa_steps (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sheet_id    UUID NOT NULL REFERENCES dsa_sheets(id) ON DELETE CASCADE,
    slug        VARCHAR(120) NOT NULL,
    order_index INT NOT NULL,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dsa_steps_sheet_slug  UNIQUE (sheet_id, slug),
    CONSTRAINT uq_dsa_steps_sheet_order UNIQUE (sheet_id, order_index)
);

COMMENT ON COLUMN dsa_steps.slug IS 'Stable URL segment. Unique per sheet, so /dsa/:stepSlug/:problemSlug never shifts.';

CREATE INDEX idx_dsa_steps_sheet ON dsa_steps (sheet_id, order_index);


-- ----------------------------------------------------------------------------
-- Sections are a tree, not a single layer: a step's section may split into
-- sub-sections, and those into further levels again.
--
-- On ordering a tree
-- ------------------
-- Problems are paginated, so the database has to be able to order them in tree
-- order without the application's help. A recursive CTE could do it at read
-- time, but it would run on every page of every step.
--
-- Instead each section stores a materialised `path`: its ancestors' order
-- indexes, zero-padded and dot-joined ('003', '003.001', '003.001.002').
-- Sorting by that string is tree order, it is a plain btree index, and it costs
-- nothing to read. The price is that the path must be rewritten when a section
-- moves, which the authoring service owns -- a fair trade for a structure that
-- is written rarely and read constantly.
--
-- Zero-padding to three digits caps a level at 999 siblings. Well past what a
-- sheet needs, and without it '10' sorts before '2'.
-- ----------------------------------------------------------------------------

CREATE TABLE dsa_sections (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    step_id           UUID NOT NULL REFERENCES dsa_steps(id) ON DELETE CASCADE,
    parent_section_id UUID REFERENCES dsa_sections(id) ON DELETE CASCADE,
    order_index       INT NOT NULL,
    depth             INT NOT NULL DEFAULT 0,
    path              VARCHAR(255) NOT NULL DEFAULT '',
    title             VARCHAR(255),
    description       VARCHAR(1000),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE dsa_sections IS
  'A grouping level inside a step, nestable to any depth. May hold problems, sub-sections, or '
  'both. A step whose problems sit in one untitled root section renders flat.';
COMMENT ON COLUMN dsa_sections.title IS
  'Nullable on purpose: the single implicit section of a flat step has no heading.';
COMMENT ON COLUMN dsa_sections.parent_section_id IS
  'Null for a top-level section. Cascades, so deleting a section takes its whole subtree.';
COMMENT ON COLUMN dsa_sections.depth IS
  'Zero for a top-level section. Derived from the parent chain; stored so the UI can indent '
  'without walking it.';
COMMENT ON COLUMN dsa_sections.path IS
  'Ancestor order indexes, zero-padded and dot-joined. Sorting by this is tree order. '
  'Maintained on write by the authoring and import services.';

CREATE INDEX idx_dsa_sections_step   ON dsa_sections (step_id, order_index);
CREATE INDEX idx_dsa_sections_parent ON dsa_sections (parent_section_id);
CREATE INDEX idx_dsa_sections_path   ON dsa_sections (step_id, path);

-- Uniqueness is per parent, not per step: two sub-sections under different
-- parents may both be the first of their group. A plain
-- UNIQUE (step_id, parent_section_id, order_index) would not constrain the top
-- level at all, because Postgres treats NULLs as distinct and every root
-- section has a NULL parent. So it takes two partial indexes.
CREATE UNIQUE INDEX uq_dsa_sections_root_order
    ON dsa_sections (step_id, order_index) WHERE parent_section_id IS NULL;

CREATE UNIQUE INDEX uq_dsa_sections_child_order
    ON dsa_sections (parent_section_id, order_index) WHERE parent_section_id IS NOT NULL;


CREATE TABLE dsa_problems (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    section_id        UUID NOT NULL REFERENCES dsa_sections(id) ON DELETE CASCADE,
    slug              VARCHAR(160) NOT NULL UNIQUE,
    order_index       INT NOT NULL,
    title             VARCHAR(255) NOT NULL,
    statement         TEXT NOT NULL DEFAULT '',
    difficulty        VARCHAR(8) NOT NULL
                      CONSTRAINT ck_dsa_problems_difficulty
                      CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    tags              JSONB NOT NULL DEFAULT '[]',
    estimated_minutes INT NOT NULL DEFAULT 20,
    youtube_url       VARCHAR(512),
    youtube_position  INT,
    practice_url      VARCHAR(512),
    practice_platform VARCHAR(32),
    status            VARCHAR(16) NOT NULL DEFAULT 'DRAFT'
                      CONSTRAINT ck_dsa_problems_status CHECK (status IN ('DRAFT', 'PUBLISHED')),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dsa_problems_section_order UNIQUE (section_id, order_index)
);

COMMENT ON COLUMN dsa_problems.slug IS
  'Stable import key. Re-importing a step matches on this and updates in place -- never '
  'delete-and-recreate, or every learner loses their progress and submissions.';
COMMENT ON COLUMN dsa_problems.statement IS
  'Markdown, written by us. Third-party problem statements are not ours to copy.';
COMMENT ON COLUMN dsa_problems.youtube_position IS
  'One-based index in the sheet playlist, for the "watch on the channel" deep link.';

CREATE INDEX idx_dsa_problems_section ON dsa_problems (section_id, order_index);
CREATE INDEX idx_dsa_problems_status  ON dsa_problems (status);


-- ----------------------------------------------------------------------------
-- Per-problem editorial depth
-- ----------------------------------------------------------------------------

CREATE TABLE dsa_approaches (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    problem_id       UUID NOT NULL REFERENCES dsa_problems(id) ON DELETE CASCADE,
    kind             VARCHAR(8) NOT NULL
                     CONSTRAINT ck_dsa_approaches_kind
                     CHECK (kind IN ('BRUTE', 'BETTER', 'OPTIMAL')),
    order_index      INT NOT NULL,
    intuition        TEXT NOT NULL DEFAULT '',
    time_complexity  VARCHAR(64),
    space_complexity VARCHAR(64),
    language         VARCHAR(24),
    code             TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dsa_approaches_problem_order UNIQUE (problem_id, order_index)
);

COMMENT ON TABLE dsa_approaches IS
  'Our editorial. The UI reveals these in order, so a learner walks past brute force '
  'before optimal appears.';

CREATE INDEX idx_dsa_approaches_problem ON dsa_approaches (problem_id, order_index);


CREATE TABLE dsa_hints (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    problem_id  UUID NOT NULL REFERENCES dsa_problems(id) ON DELETE CASCADE,
    order_index INT NOT NULL,
    body        TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dsa_hints_problem_order UNIQUE (problem_id, order_index)
);

COMMENT ON TABLE dsa_hints IS 'Progressive hints, revealed one at a time rather than paywalled.';

CREATE INDEX idx_dsa_hints_problem ON dsa_hints (problem_id, order_index);


CREATE TABLE dsa_harnesses (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    problem_id         UUID NOT NULL REFERENCES dsa_problems(id) ON DELETE CASCADE,
    language           VARCHAR(24) NOT NULL,
    starter_code       TEXT NOT NULL,
    driver_code        TEXT NOT NULL,
    reference_solution TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dsa_harnesses_problem_lang UNIQUE (problem_id, language),
    CONSTRAINT ck_dsa_harnesses_placeholder
        CHECK (position('{{USER_CODE}}' in driver_code) > 0)
);

COMMENT ON TABLE  dsa_harnesses IS
  'What turns a fragment into a program. One row per problem per language.';
COMMENT ON COLUMN dsa_harnesses.starter_code IS
  'The stub the editor shows. The only column of this table a learner ever sees.';
COMMENT ON COLUMN dsa_harnesses.driver_code IS
  'Full compilable program with {{USER_CODE}} where the learner''s class is spliced in. '
  'Reads a case count from stdin, loops, prints a delimiter after each case. NEVER '
  'serialised to a non-admin client -- it embeds the I/O contract and often the answer shape.';
COMMENT ON COLUMN dsa_harnesses.reference_solution IS
  'Our own working solution. Drives the generate-expected-output action. Never serialised '
  'to a non-admin client.';

CREATE INDEX idx_dsa_harnesses_problem ON dsa_harnesses (problem_id);


CREATE TABLE dsa_test_cases (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    problem_id      UUID NOT NULL REFERENCES dsa_problems(id) ON DELETE CASCADE,
    order_index     INT NOT NULL,
    input           TEXT NOT NULL,
    expected_output TEXT NOT NULL DEFAULT '',
    is_sample       BOOLEAN NOT NULL DEFAULT FALSE,
    explanation     TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dsa_test_cases_problem_order UNIQUE (problem_id, order_index)
);

COMMENT ON COLUMN dsa_test_cases.is_sample IS
  'Sample cases are public: they render as the Examples in the statement and are the only '
  'ones Run executes. Non-sample rows and their expected output are admin-only.';
COMMENT ON COLUMN dsa_test_cases.expected_output IS
  'Defaults to empty so a case can be imported before the reference solution has generated it.';

CREATE INDEX idx_dsa_test_cases_problem ON dsa_test_cases (problem_id, order_index);


CREATE TABLE dsa_checks (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    problem_id     UUID NOT NULL REFERENCES dsa_problems(id) ON DELETE CASCADE,
    order_index    INT NOT NULL DEFAULT 1,
    prompt         TEXT NOT NULL,
    options        JSONB NOT NULL DEFAULT '[]',
    correct_answer VARCHAR(512) NOT NULL,
    explanation    TEXT,
    points         INT NOT NULL DEFAULT 2,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dsa_checks_problem_order UNIQUE (problem_id, order_index)
);

COMMENT ON TABLE  dsa_checks IS
  'The inline "now your turn" question inside a statement. Answered against the server.';
COMMENT ON COLUMN dsa_checks.correct_answer IS
  'Stripped from every learner-facing response and compared server-side, the same rule the '
  'subtopic quiz already follows.';

CREATE INDEX idx_dsa_checks_problem ON dsa_checks (problem_id, order_index);


-- ----------------------------------------------------------------------------
-- Per-learner DSA data
--
-- Saved-for-later lives in `bookmarks` (SECTION 5) rather than as a flag here,
-- and notes live in `notes` for the same reason.
-- ----------------------------------------------------------------------------

CREATE TABLE user_dsa_problem_progress (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    problem_id    UUID NOT NULL REFERENCES dsa_problems(id) ON DELETE CASCADE,
    status        VARCHAR(16) NOT NULL DEFAULT 'NOT_STARTED'
                  CONSTRAINT ck_user_dsa_progress_status
                  CHECK (status IN ('NOT_STARTED', 'ATTEMPTED', 'SOLVED')),
    attempt_count INT NOT NULL DEFAULT 0,
    last_language VARCHAR(24),
    solved_at     TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_dsa_progress UNIQUE (user_id, problem_id)
);

COMMENT ON COLUMN user_dsa_problem_progress.solved_at IS
  'Also the once-ever points guard: points are awarded only on the transition from null.';

CREATE INDEX idx_user_dsa_progress_user    ON user_dsa_problem_progress (user_id);
CREATE INDEX idx_user_dsa_progress_problem ON user_dsa_problem_progress (problem_id);


CREATE TABLE user_dsa_submissions (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    problem_id   UUID NOT NULL REFERENCES dsa_problems(id) ON DELETE CASCADE,
    language     VARCHAR(24) NOT NULL,
    code         TEXT NOT NULL,
    verdict      VARCHAR(16) NOT NULL
                 CONSTRAINT ck_user_dsa_submissions_verdict
                 CHECK (verdict IN ('ACCEPTED', 'WRONG_ANSWER', 'COMPILE_ERROR',
                                    'RUNTIME_ERROR', 'TIME_LIMIT', 'ENGINE_ERROR')),
    passed_count INT NOT NULL DEFAULT 0,
    total_count  INT NOT NULL DEFAULT 0,
    runtime_ms   INT,
    memory_kb    BIGINT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE user_dsa_submissions IS
  'Every Submit, pass or fail. ENGINE_ERROR rows are recorded for diagnostics but never '
  'count as an attempt against the learner.';

CREATE INDEX idx_user_dsa_submissions_user_problem
    ON user_dsa_submissions (user_id, problem_id, created_at DESC);


-- ============================================================================
-- SECTION 5 — Learner-authored data
--
-- One notes table and one bookmarks table, across every kind of content. "My
-- notes" and "my bookmarks" are then single queries the UI can filter, rather
-- than a union that grows a branch every time a new kind of thing becomes
-- noteable.
--
-- On the shape of the target reference
-- ------------------------------------
-- The obvious way to point at "any kind of thing" is a (target_type, target_id)
-- pair. It is rejected here: target_id can carry no foreign key, so deleting a
-- topic would silently leave notes pointing at nothing, and this schema's
-- conventions commit to indexing and cascading every reference.
--
-- Instead there is one nullable, properly-constrained FK column per target kind
-- and a CHECK that exactly one is populated. That keeps ON DELETE CASCADE doing
-- its job, keeps every reference indexed, and makes "only DSA bookmarks" a
-- plain indexed predicate. The cost is that a fourth kind of target needs a
-- migration rather than a new enum value -- which is a fair price for not being
-- able to orphan a row, and forces a moment's thought about cascade behaviour
-- each time.
--
-- These tables sit last because they reference both content trees.
-- ============================================================================

CREATE TABLE notes (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    subtopic_id    UUID REFERENCES subtopics(id)    ON DELETE CASCADE,
    topic_id       UUID REFERENCES topics(id)       ON DELETE CASCADE,
    dsa_problem_id UUID REFERENCES dsa_problems(id) ON DELETE CASCADE,

    content        TEXT NOT NULL DEFAULT '',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_notes_exactly_one_target
        CHECK (num_nonnulls(subtopic_id, topic_id, dsa_problem_id) = 1)
);

COMMENT ON TABLE  notes IS
  'Private learner notes against any kind of content. Exactly one target column is set; '
  'which one it is *is* the note''s type, so there is no separate discriminator to keep honest.';
COMMENT ON COLUMN notes.content IS
  'Markdown. Rendered through an escaping renderer, never as raw HTML.';
COMMENT ON CONSTRAINT ck_notes_exactly_one_target ON notes IS
  'Rejects both a note pointing at nothing and a note pointing at two things at once.';

-- Uniqueness is per target kind, so the partial indexes double as the lookup
-- indexes for each kind. A plain UNIQUE across all three columns would treat
-- NULLs as distinct and let a learner accumulate duplicate notes on one target.
CREATE UNIQUE INDEX uq_notes_subtopic
    ON notes (user_id, subtopic_id) WHERE subtopic_id IS NOT NULL;
CREATE UNIQUE INDEX uq_notes_topic
    ON notes (user_id, topic_id) WHERE topic_id IS NOT NULL;
CREATE UNIQUE INDEX uq_notes_dsa_problem
    ON notes (user_id, dsa_problem_id) WHERE dsa_problem_id IS NOT NULL;

CREATE INDEX idx_notes_user ON notes (user_id);


CREATE TABLE bookmarks (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    topic_id       UUID REFERENCES topics(id)       ON DELETE CASCADE,
    dsa_problem_id UUID REFERENCES dsa_problems(id) ON DELETE CASCADE,

    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_bookmarks_exactly_one_target
        CHECK (num_nonnulls(topic_id, dsa_problem_id) = 1)
);

COMMENT ON TABLE bookmarks IS
  'Saved-for-later, across content types. A DSA problem marked for revision is a bookmark '
  'like any other -- the two were the same idea wearing different clothes.';

CREATE UNIQUE INDEX uq_bookmarks_topic
    ON bookmarks (user_id, topic_id) WHERE topic_id IS NOT NULL;
CREATE UNIQUE INDEX uq_bookmarks_dsa_problem
    ON bookmarks (user_id, dsa_problem_id) WHERE dsa_problem_id IS NOT NULL;

CREATE INDEX idx_bookmarks_user ON bookmarks (user_id, created_at DESC);


-- ============================================================================
-- SECTION 6 — Code playground
-- ============================================================================

CREATE TABLE shared_snippets (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Short, URL-safe, and drawn from an alphabet with look-alike characters
    -- removed, so a link survives being read aloud or retyped.
    short_id         VARCHAR(12) NOT NULL UNIQUE,
    -- SHA-256 of language + code. Unique, so re-sharing identical code returns
    -- the existing link instead of creating another row.
    code_hash        VARCHAR(64) NOT NULL UNIQUE,
    language         VARCHAR(30) NOT NULL,
    code             TEXT NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_accessed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  shared_snippets IS 'Publicly readable code snippets addressed by short link.';
COMMENT ON COLUMN shared_snippets.code_hash IS 'Deduplication key; identical code reuses the existing short link.';
COMMENT ON COLUMN shared_snippets.last_accessed_at IS 'Retention signal. Not updated on every read — that would make a public GET a write.';

-- short_id and code_hash are already indexed by their UNIQUE constraints.
CREATE INDEX idx_shared_snippets_last_accessed ON shared_snippets (last_accessed_at);


-- ============================================================================
-- SECTION 7 — Payments
--
-- Donations only; nothing here gates access to content.
-- ============================================================================

CREATE TABLE donation_orders (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Gateway order identifier. Unique, so a repeated verification callback or
    -- webhook delivery settles the same order rather than duplicating it.
    order_id    VARCHAR(100) NOT NULL UNIQUE,
    payment_id  VARCHAR(100),
    signature   VARCHAR(255),
    -- Whole currency units, not minor units. Converted to paise at the gateway
    -- boundary, and the captured amount is reconciled against this on webhook.
    amount      INTEGER NOT NULL CONSTRAINT ck_donation_amount CHECK (amount > 0),
    currency    VARCHAR(10) NOT NULL DEFAULT 'INR',
    status      VARCHAR(30) NOT NULL DEFAULT 'CREATED'
                CONSTRAINT ck_donation_status
                    CHECK (status IN ('CREATED', 'COMPLETED', 'FAILED')),
    donor_name  VARCHAR(255),
    donor_email VARCHAR(255),
    message     TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  donation_orders IS 'Voluntary contributions. COMPLETED is terminal and never downgraded.';
COMMENT ON COLUMN donation_orders.amount IS 'Whole currency units. Reconciled against the gateway-captured amount before settling.';
COMMENT ON COLUMN donation_orders.signature IS 'Gateway signature retained for audit after successful verification.';

-- order_id is already indexed by its UNIQUE constraint.
CREATE INDEX idx_donation_orders_status ON donation_orders (status);


-- ============================================================================
-- SECTION 8 — updated_at triggers
-- ============================================================================

CREATE TRIGGER trg_paths_updated_at
    BEFORE UPDATE ON paths
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_topics_updated_at
    BEFORE UPDATE ON topics
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_subtopics_updated_at
    BEFORE UPDATE ON subtopics
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_prefs_updated_at
    BEFORE UPDATE ON user_learning_preferences
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_notes_updated_at
    BEFORE UPDATE ON notes
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_donation_orders_updated_at
    BEFORE UPDATE ON donation_orders
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_dsa_sheets_updated_at        BEFORE UPDATE ON dsa_sheets                FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_dsa_steps_updated_at         BEFORE UPDATE ON dsa_steps                 FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_dsa_sections_updated_at      BEFORE UPDATE ON dsa_sections              FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_dsa_problems_updated_at      BEFORE UPDATE ON dsa_problems              FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_dsa_approaches_updated_at    BEFORE UPDATE ON dsa_approaches            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_dsa_harnesses_updated_at     BEFORE UPDATE ON dsa_harnesses             FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_dsa_test_cases_updated_at    BEFORE UPDATE ON dsa_test_cases            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_dsa_checks_updated_at        BEFORE UPDATE ON dsa_checks                FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_user_dsa_progress_updated_at BEFORE UPDATE ON user_dsa_problem_progress FOR EACH ROW EXECUTE FUNCTION set_updated_at();
