-- ============================================================================
-- learnNow — baseline schema
-- ============================================================================
--
-- Consolidates the previous V1–V5 migrations into a single baseline. Those were
-- incremental steps taken before the platform had been deployed anywhere, so
-- there is no history worth preserving and a great deal of noise worth removing:
-- the old V1 created a topics.path_id column that V4 superseded with a join
-- table and never dropped, leaving two sources of truth for the same
-- relationship. That ambiguity was a live bug — topics attached through the
-- admin UI had a null path_id, and code reading it crashed — so the column is
-- gone here rather than carried forward.
--
-- Conventions used throughout:
--
--   * Surrogate keys are UUID, generated by the database. Users are the one
--     exception: their id is an application-issued string, since accounts may
--     originate from an external identity provider.
--   * Timestamps are TIMESTAMPTZ. Never TIMESTAMP — learners span time zones
--     and streaks are computed against a stored per-user zone.
--   * Every foreign key is indexed. Postgres does not do this automatically,
--     and without it each cascade delete degrades into a sequential scan.
--   * Anything owned by a user cascades from it, so deleting an account removes
--     its data in one statement.
--   * Status and type columns are constrained by CHECK rather than left as free
--     text, so a typo in application code fails at write time rather than
--     becoming a row nothing will ever match.
--   * Tables and non-obvious columns carry COMMENT metadata, which surfaces in
--     psql (\d+) and any schema browser.
--
-- Ordering below follows dependency order: content, then identity, then the
-- per-user data that references both.
-- ============================================================================

-- gen_random_uuid() lives in pgcrypto before Postgres 13 and in core after.
-- Requesting it explicitly keeps this migration portable across both.
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- ----------------------------------------------------------------------------
-- Shared trigger for updated_at.
--
-- Some tables map updated_at through JPA and some do not, which would leave the
-- column silently stale on the ones that do not -- worse than having no column
-- at all, since it reads as trustworthy. Maintaining it in the database makes
-- it true for every writer, including migrations and manual fixes.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_updated_at() IS 'BEFORE UPDATE trigger; stamps updated_at so the column cannot go stale.';


-- ============================================================================
-- SECTION 1 — Course content
--
-- A path is a course. A topic is a chapter within it, and a subtopic is a
-- lesson within that. Paths and topics are many-to-many: a topic such as
-- "HTTP fundamentals" belongs in several courses without being duplicated.
-- ============================================================================

CREATE TABLE paths (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    category    VARCHAR(255),
    managed_by  VARCHAR(255),
    status      VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED'
                CONSTRAINT ck_paths_status CHECK (status IN ('DRAFT', 'PUBLISHED')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  paths IS 'A learning path — one course, containing an ordered set of topics.';
COMMENT ON COLUMN paths.status IS 'DRAFT is visible only to admins; PUBLISHED is public.';
COMMENT ON COLUMN paths.managed_by IS 'Attribution shown to learners, e.g. the authoring team.';

CREATE INDEX idx_paths_status ON paths (status);


CREATE TABLE topics (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    duration    VARCHAR(255),
    category    VARCHAR(255),
    -- Fallback ordering for a topic viewed outside any path. Ordering *within*
    -- a path lives on path_topics, because the same topic can sit at a
    -- different position in each course that includes it.
    order_index INTEGER NOT NULL DEFAULT 1,
    status      VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED'
                CONSTRAINT ck_topics_status CHECK (status IN ('DRAFT', 'PUBLISHED')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  topics IS 'A chapter of study. Shared across paths via path_topics; a topic has no single owning path.';
COMMENT ON COLUMN topics.duration IS 'Human-readable estimate shown in the UI, e.g. "45 mins". Not used for arithmetic.';
COMMENT ON COLUMN topics.order_index IS 'Fallback ordering only. Position within a path is path_topics.order_index.';

CREATE INDEX idx_topics_status ON topics (status);


CREATE TABLE path_topics (
    path_id     UUID NOT NULL REFERENCES paths(id)  ON DELETE CASCADE,
    topic_id    UUID NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    order_index INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (path_id, topic_id)
);

COMMENT ON TABLE  path_topics IS 'Single source of truth for path membership, with per-path ordering.';
COMMENT ON COLUMN path_topics.order_index IS 'Position of this topic within this path. The same topic may be ordered differently elsewhere.';

-- The composite primary key already indexes (path_id, ...), so only the reverse
-- direction and the ordered read need their own indexes.
CREATE INDEX idx_path_topics_topic ON path_topics (topic_id);
CREATE INDEX idx_path_topics_order ON path_topics (path_id, order_index);


CREATE TABLE subtopics (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    topic_id          UUID NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    title             VARCHAR(255) NOT NULL,
    content           TEXT,
    order_index       INTEGER NOT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED'
                      CONSTRAINT ck_subtopics_status CHECK (status IN ('DRAFT', 'PUBLISHED')),
    -- Bumped on each publish. Progress rows record the version a learner
    -- answered against, so substantive edits can be told apart from typo fixes.
    version           INTEGER NOT NULL DEFAULT 1,
    -- Deliberately unconstrained. Both are content taxonomy supplied by course
    -- authors through the bulk importer, so a CHECK here would turn a new label
    -- into a migration and reject an otherwise valid import at the database
    -- layer, where the error cannot be reported usefully. Validate at the API
    -- boundary instead. Conventional values: level is beginner | intermediate |
    -- advanced; track is concept | lab | project.
    level             VARCHAR(20) NOT NULL DEFAULT 'beginner',
    track             VARCHAR(30) NOT NULL DEFAULT 'concept',
    -- JSON array of subtopic titles that should be completed first. Advisory,
    -- not enforced by the application.
    prerequisites     JSONB NOT NULL DEFAULT '[]',
    video_url         VARCHAR(512),
    -- Zero is permitted: an author may legitimately not have estimated a lesson.
    estimated_minutes INTEGER NOT NULL DEFAULT 5
                      CONSTRAINT ck_subtopics_minutes CHECK (estimated_minutes >= 0),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  subtopics IS 'A single lesson. The smallest unit a learner completes.';
COMMENT ON COLUMN subtopics.version IS 'Incremented on publish; compared against user_subtopic_progress.content_version_answered.';
COMMENT ON COLUMN subtopics.prerequisites IS 'JSON array of prerequisite subtopic titles. Advisory.';
COMMENT ON COLUMN subtopics.level IS 'Author-supplied difficulty label. Open vocabulary; validated at the API boundary, not here.';
COMMENT ON COLUMN subtopics.track IS 'Author-supplied lesson kind. Open vocabulary; validated at the API boundary, not here.';

-- Covers both the foreign key and the ordered read of a topic's lessons.
CREATE INDEX idx_subtopics_topic_order ON subtopics (topic_id, order_index);


CREATE TABLE subtopic_code_snippets (
    id              VARCHAR(100) NOT NULL,
    subtopic_id     UUID NOT NULL REFERENCES subtopics(id) ON DELETE CASCADE,
    language        VARCHAR(30) NOT NULL,
    label           VARCHAR(255),
    code            TEXT NOT NULL,
    expected_output TEXT,
    runnable        BOOLEAN NOT NULL DEFAULT TRUE,
    editable        BOOLEAN NOT NULL DEFAULT TRUE,
    order_index     INTEGER NOT NULL DEFAULT 1,
    -- Author-assigned id, unique only within its subtopic, so imports can
    -- reference snippets by a stable readable name.
    PRIMARY KEY (subtopic_id, id)
);

COMMENT ON TABLE  subtopic_code_snippets IS 'Runnable examples attached to a lesson, shown in the embedded playground.';
COMMENT ON COLUMN subtopic_code_snippets.runnable IS 'Whether the learner may execute it, as opposed to only reading it.';
COMMENT ON COLUMN subtopic_code_snippets.expected_output IS 'Optional; lets the UI show what correct output looks like.';

CREATE INDEX idx_snippets_subtopic ON subtopic_code_snippets (subtopic_id);


CREATE TABLE content_blocks (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    subtopic_id UUID NOT NULL REFERENCES subtopics(id) ON DELETE CASCADE,
    order_index INTEGER NOT NULL,
    type        VARCHAR(20) NOT NULL
                CONSTRAINT ck_content_blocks_type
                    CHECK (type IN ('markdown', 'quiz', 'callout', 'code')),
    body        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  content_blocks IS 'Ordered blocks making up a lesson body.';
COMMENT ON COLUMN content_blocks.type IS 'markdown and callout use body; quiz draws from quiz_questions instead.';

CREATE INDEX idx_content_blocks_subtopic_order ON content_blocks (subtopic_id, order_index);


CREATE TABLE quiz_questions (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    block_id       UUID NOT NULL REFERENCES content_blocks(id) ON DELETE CASCADE,
    kind           VARCHAR(20) NOT NULL
                   CONSTRAINT ck_quiz_questions_kind
                       CHECK (kind IN ('mcq', 'true_false', 'fill_blank')),
    prompt         TEXT NOT NULL,
    -- JSON array of choices. Null for fill_blank.
    options        JSONB,
    -- Compared case-insensitively, server-side only. Never sent to a client
    -- before the attempt is settled.
    correct_answer TEXT NOT NULL,
    explanation    TEXT,
    points         INTEGER NOT NULL DEFAULT 5
                   CONSTRAINT ck_quiz_questions_points CHECK (points >= 0)
);

COMMENT ON TABLE  quiz_questions IS 'Questions belonging to a quiz content block. Grading is server-side.';
COMMENT ON COLUMN quiz_questions.correct_answer IS 'Withheld from responses until the attempt is settled, so a wrong answer cannot reveal it.';
COMMENT ON COLUMN quiz_questions.points IS 'Awarded on the first correct attempt only. See user_quiz_attempts.';

CREATE INDEX idx_quiz_questions_block ON quiz_questions (block_id);


-- ============================================================================
-- SECTION 2 — Identity and credentials
--
-- Every token table stores only a SHA-256 hash of the value handed to the user,
-- so a database disclosure yields nothing that can be replayed.
-- ============================================================================

CREATE TABLE users (
    -- Application-issued rather than database-generated, because an account may
    -- originate from an external identity provider.
    id             VARCHAR(255) PRIMARY KEY,
    email          VARCHAR(255) NOT NULL,
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    full_name      VARCHAR(255),
    -- Null for accounts that authenticate only through Google.
    password_hash  VARCHAR(255),
    google_sub     VARCHAR(255) UNIQUE,
    avatar         VARCHAR(512),
    role           VARCHAR(50) NOT NULL DEFAULT 'USER'
                   CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN')),
    bio            VARCHAR(500),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    -- Incremented to invalidate every access token issued so far, without
    -- needing a database read on each request.
    token_version  INTEGER NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  users IS 'Learner and administrator accounts.';
COMMENT ON COLUMN users.id IS 'Application-issued identifier, not a database sequence.';
COMMENT ON COLUMN users.password_hash IS 'BCrypt. Null when the account authenticates only via Google.';
COMMENT ON COLUMN users.google_sub IS 'Google subject claim. Unique so one Google identity maps to one account.';
COMMENT ON COLUMN users.token_version IS 'Bumped on password reset; refuses refresh tokens minted before the change.';

-- Addresses are matched case-insensitively throughout, so uniqueness has to be
-- enforced the same way. A plain UNIQUE would let Ada@x.com and ada@x.com
-- coexist and create two accounts for one mailbox.
CREATE UNIQUE INDEX uq_users_email_lower ON users (LOWER(email));


CREATE TABLE email_verification_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  email_verification_tokens IS 'Single-use email confirmation grants. Purged nightly once used or expired.';
COMMENT ON COLUMN email_verification_tokens.token_hash IS 'SHA-256 of the token in the emailed link; the token itself is never stored.';

CREATE INDEX idx_email_verification_user    ON email_verification_tokens (user_id);
CREATE INDEX idx_email_verification_expires ON email_verification_tokens (expires_at);


CREATE TABLE password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  password_reset_tokens IS 'Single-use password reset grants, valid for one hour.';

CREATE INDEX idx_password_reset_user    ON password_reset_tokens (user_id);
CREATE INDEX idx_password_reset_expires ON password_reset_tokens (expires_at);


CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  refresh_tokens IS 'Renewal grants. Rows exist so a session can actually be revoked, which a bare JWT cannot be.';
COMMENT ON COLUMN refresh_tokens.revoked IS 'Set on sign-out, on rotation, and for every row on password reset.';

CREATE INDEX idx_refresh_token_user    ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_token_expires ON refresh_tokens (expires_at);


-- ============================================================================
-- SECTION 3 — Progress and gamification
--
-- Completion is one-way: points are awarded on the transition and never
-- reversed, so a reversible transition would be a way to mint them.
-- ============================================================================

CREATE TABLE user_learning_preferences (
    user_id            VARCHAR(255) PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    -- Streaks are day-boundary sensitive, so "today" must be evaluated in the
    -- learner's own zone rather than the server's.
    timezone           VARCHAR(64) NOT NULL DEFAULT 'Asia/Kolkata',
    current_streak     INTEGER NOT NULL DEFAULT 0
                       CONSTRAINT ck_prefs_current_streak CHECK (current_streak >= 0),
    longest_streak     INTEGER NOT NULL DEFAULT 0
                       CONSTRAINT ck_prefs_longest_streak CHECK (longest_streak >= 0),
    last_activity_date DATE,
    total_points       INTEGER NOT NULL DEFAULT 0
                       CONSTRAINT ck_prefs_total_points CHECK (total_points >= 0),
    -- Optimistic lock. Point awards are read-modify-write, so without it two
    -- concurrent awards silently lose one of the two increments.
    version            BIGINT NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  user_learning_preferences IS 'Per-learner settings and lifetime gamification totals.';
COMMENT ON COLUMN user_learning_preferences.timezone IS 'IANA zone id. Streak day boundaries are evaluated in it.';
COMMENT ON COLUMN user_learning_preferences.version IS 'JPA @Version. Guards concurrent point awards.';


CREATE TABLE user_topic_progress (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      VARCHAR(255) NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
    topic_id     UUID NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    -- Denormalised deliberately: records which path the learner was working
    -- through when they completed it, which path_topics cannot answer once a
    -- topic belongs to several.
    path_id      UUID NOT NULL REFERENCES paths(id)  ON DELETE CASCADE,
    status       VARCHAR(16) NOT NULL DEFAULT 'NOT_STARTED'
                 CONSTRAINT ck_utp_status
                     CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED')),
    completed_at TIMESTAMPTZ,
    CONSTRAINT uq_utp_user_topic UNIQUE (user_id, topic_id)
);

COMMENT ON TABLE  user_topic_progress IS 'A learner''s state for one topic. One row per user and topic.';
COMMENT ON COLUMN user_topic_progress.path_id IS 'The path the learner was in at the time; a topic can belong to several.';

CREATE INDEX idx_utp_user_path_status ON user_topic_progress (user_id, path_id, status);
CREATE INDEX idx_utp_topic            ON user_topic_progress (topic_id);


CREATE TABLE user_subtopic_progress (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                  VARCHAR(255) NOT NULL REFERENCES users(id)     ON DELETE CASCADE,
    subtopic_id              UUID NOT NULL REFERENCES subtopics(id) ON DELETE CASCADE,
    -- Denormalised so "how many lessons of this topic are done" is a single
    -- indexed count rather than a join back through subtopics.
    topic_id                 UUID NOT NULL REFERENCES topics(id)    ON DELETE CASCADE,
    completed                BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at             TIMESTAMPTZ,
    content_version_answered INTEGER,
    first_attempt_correct    BOOLEAN,
    CONSTRAINT uq_usp_user_subtopic UNIQUE (user_id, subtopic_id)
);

COMMENT ON TABLE  user_subtopic_progress IS 'A learner''s state for one lesson.';
COMMENT ON COLUMN user_subtopic_progress.topic_id IS 'Denormalised from subtopics to keep per-topic completion counts a single indexed read.';
COMMENT ON COLUMN user_subtopic_progress.content_version_answered IS 'subtopics.version at completion, so later edits can be detected.';

CREATE INDEX idx_usp_user_topic_completed ON user_subtopic_progress (user_id, topic_id, completed);
CREATE INDEX idx_usp_subtopic             ON user_subtopic_progress (subtopic_id);


CREATE TABLE user_quiz_attempts (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        VARCHAR(255) NOT NULL REFERENCES users(id)          ON DELETE CASCADE,
    question_id    UUID NOT NULL REFERENCES quiz_questions(id) ON DELETE CASCADE,
    is_correct     BOOLEAN NOT NULL,
    points_awarded INTEGER NOT NULL DEFAULT 0
                   CONSTRAINT ck_quiz_attempt_points CHECK (points_awarded >= 0),
    attempted_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- This constraint is the actual enforcement of first-attempt-only scoring.
    -- An application-level check alone still loses the race between two
    -- concurrent submissions for the same question.
    CONSTRAINT uq_quiz_attempt_user_question UNIQUE (user_id, question_id)
);

COMMENT ON TABLE  user_quiz_attempts IS 'One row per learner per question. Its existence is what stops points being farmed by replay.';
COMMENT ON COLUMN user_quiz_attempts.points_awarded IS 'Non-zero only on a correct first attempt.';

CREATE INDEX idx_quiz_attempt_user ON user_quiz_attempts (user_id);


CREATE TABLE user_learning_daily_activity (
    id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- A calendar date in the learner's own time zone, not UTC.
    activity_date          DATE NOT NULL,
    first_activity_at      TIMESTAMPTZ NOT NULL,
    last_activity_at       TIMESTAMPTZ NOT NULL,
    qualifying_event_count INTEGER NOT NULL DEFAULT 0,
    points_earned          INTEGER NOT NULL DEFAULT 0
                           CONSTRAINT ck_daily_points CHECK (points_earned >= 0),
    CONSTRAINT uq_daily_user_date UNIQUE (user_id, activity_date)
);

COMMENT ON TABLE  user_learning_daily_activity IS 'Daily rollup driving the streak calendar and weekly leaderboard.';
COMMENT ON COLUMN user_learning_daily_activity.activity_date IS 'Local date in the learner''s configured zone.';
COMMENT ON COLUMN user_learning_daily_activity.qualifying_event_count IS 'Actions that count towards keeping a streak alive.';

CREATE INDEX idx_daily_activity_user_date ON user_learning_daily_activity (user_id, activity_date DESC);


-- ============================================================================
-- SECTION 4 — Learner-authored data
-- ============================================================================

CREATE TABLE subtopic_notes (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     VARCHAR(255) NOT NULL REFERENCES users(id)     ON DELETE CASCADE,
    subtopic_id UUID NOT NULL REFERENCES subtopics(id) ON DELETE CASCADE,
    content     TEXT NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_notes_user_subtopic UNIQUE (user_id, subtopic_id)
);

COMMENT ON TABLE  subtopic_notes IS 'Private per-lesson notes. Visible only to their author.';
COMMENT ON COLUMN subtopic_notes.content IS 'Markdown. Rendered through an escaping renderer, never as raw HTML.';

CREATE INDEX idx_subtopic_notes_user ON subtopic_notes (user_id);
CREATE INDEX idx_subtopic_notes_subtopic ON subtopic_notes (subtopic_id);


CREATE TABLE topic_bookmarks (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    VARCHAR(255) NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
    topic_id   UUID NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_bookmarks_user_topic UNIQUE (user_id, topic_id)
);

COMMENT ON TABLE topic_bookmarks IS 'Topics a learner saved for later.';

CREATE INDEX idx_topic_bookmarks_user  ON topic_bookmarks (user_id);
CREATE INDEX idx_topic_bookmarks_topic ON topic_bookmarks (topic_id);


-- ============================================================================
-- SECTION 5 — Code playground
-- ============================================================================

CREATE TABLE shared_snippets (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Short, URL-safe, and drawn from an alphabet with look-alike characters
    -- removed, so a link survives being read aloud or retyped.
    short_id         VARCHAR(12) NOT NULL UNIQUE,
    -- SHA-256 of language + code. Unique, so re-sharing identical code returns
    -- the existing link instead of creating another row.
    code_hash        VARCHAR(64) NOT NULL UNIQUE,
    language         VARCHAR(30) NOT NULL,
    code             TEXT NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_accessed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  shared_snippets IS 'Publicly readable code snippets addressed by short link.';
COMMENT ON COLUMN shared_snippets.code_hash IS 'Deduplication key; identical code reuses the existing short link.';
COMMENT ON COLUMN shared_snippets.last_accessed_at IS 'Retention signal. Not updated on every read — that would make a public GET a write.';

-- short_id and code_hash are already indexed by their UNIQUE constraints.
CREATE INDEX idx_shared_snippets_last_accessed ON shared_snippets (last_accessed_at);


-- ============================================================================
-- SECTION 6 — Payments
--
-- Donations only; nothing here gates access to content.
-- ============================================================================

CREATE TABLE donation_orders (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Gateway order identifier. Unique, so a repeated verification callback or
    -- webhook delivery settles the same order rather than duplicating it.
    order_id    VARCHAR(100) NOT NULL UNIQUE,
    payment_id  VARCHAR(100),
    signature   VARCHAR(255),
    -- Whole currency units, not minor units. Converted to paise at the gateway
    -- boundary, and the captured amount is reconciled against this on webhook.
    amount      INTEGER NOT NULL CONSTRAINT ck_donation_amount CHECK (amount > 0),
    currency    VARCHAR(10) NOT NULL DEFAULT 'INR',
    status      VARCHAR(30) NOT NULL DEFAULT 'CREATED'
                CONSTRAINT ck_donation_status
                    CHECK (status IN ('CREATED', 'COMPLETED', 'FAILED')),
    donor_name  VARCHAR(255),
    donor_email VARCHAR(255),
    message     TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  donation_orders IS 'Voluntary contributions. COMPLETED is terminal and never downgraded.';
COMMENT ON COLUMN donation_orders.amount IS 'Whole currency units. Reconciled against the gateway-captured amount before settling.';
COMMENT ON COLUMN donation_orders.signature IS 'Gateway signature retained for audit after successful verification.';

-- order_id is already indexed by its UNIQUE constraint.
CREATE INDEX idx_donation_orders_status ON donation_orders (status);


-- ============================================================================
-- SECTION 7 — updated_at triggers
-- ============================================================================

CREATE TRIGGER trg_paths_updated_at
    BEFORE UPDATE ON paths
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_topics_updated_at
    BEFORE UPDATE ON topics
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_subtopics_updated_at
    BEFORE UPDATE ON subtopics
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_prefs_updated_at
    BEFORE UPDATE ON user_learning_preferences
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_notes_updated_at
    BEFORE UPDATE ON subtopic_notes
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_donation_orders_updated_at
    BEFORE UPDATE ON donation_orders
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
