-- V5__security_and_integrity.sql
-- Closes data-integrity gaps found in the production-readiness audit.

-- ---------------------------------------------------------------------------
-- 1. Password reset tokens
-- There was previously no recovery path at all for password accounts. Same
-- hashed single-use pattern as email verification: only the hash is stored, so
-- a database leak does not yield usable reset links.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_password_reset_user ON password_reset_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_expires ON password_reset_tokens(expires_at);

-- ---------------------------------------------------------------------------
-- 2. Quiz attempts
-- Points were awarded on every correct submission with no record that the
-- question had already been answered, so replaying one request farmed points
-- without limit. The unique constraint is what actually enforces first-attempt
-- scoring; the application check alone would still race.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_quiz_attempts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    question_id UUID NOT NULL REFERENCES quiz_questions(id) ON DELETE CASCADE,
    is_correct BOOLEAN NOT NULL,
    points_awarded INTEGER NOT NULL DEFAULT 0,
    attempted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, question_id)
);
CREATE INDEX IF NOT EXISTS idx_quiz_attempt_user ON user_quiz_attempts(user_id);

-- ---------------------------------------------------------------------------
-- 3. Missing foreign key on email verification tokens
-- Every other user-scoped table cascades from users; this one did not, so
-- deleting a user orphaned its tokens.
-- ---------------------------------------------------------------------------
DELETE FROM email_verification_tokens
WHERE user_id NOT IN (SELECT id FROM users);

ALTER TABLE email_verification_tokens
    DROP CONSTRAINT IF EXISTS fk_email_verification_user;
ALTER TABLE email_verification_tokens
    ADD CONSTRAINT fk_email_verification_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- ---------------------------------------------------------------------------
-- 4. Optimistic locking on point totals
-- Point awards were read-modify-write with no version column, so concurrent
-- awards silently lost one of the two.
-- ---------------------------------------------------------------------------
ALTER TABLE user_learning_preferences
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

-- ---------------------------------------------------------------------------
-- 5. Refresh tokens and token versioning
-- Access tokens previously lived seven days with no way to withdraw one. They
-- are now short-lived, and renewal goes through a refresh token that exists as
-- a row here - so it can actually be revoked. token_version invalidates every
-- outstanding access token for a user at once (used on password reset).
-- ---------------------------------------------------------------------------
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS token_version INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_refresh_token_user ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_token_expires ON refresh_tokens(expires_at);

-- ---------------------------------------------------------------------------
-- 6. Backfill path_topics for any topic that still only has the legacy column
-- V4 introduced the join table but left topics.path_id in place as a second
-- source of truth. Topics attached through the admin UI never set path_id,
-- and code reading topic.getPath() therefore hit a null. The join table is now
-- the single source of truth; the legacy column is dropped in V6 once the
-- application no longer reads it.
-- ---------------------------------------------------------------------------
INSERT INTO path_topics (path_id, topic_id, order_index)
SELECT path_id, id, COALESCE(order_index, 1)
FROM topics
WHERE path_id IS NOT NULL
ON CONFLICT (path_id, topic_id) DO NOTHING;
